# fly.toml app configuration file generated for spotify-animation on 2025-07-13T21:02:44+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'spotify-animation'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[http_service.http_options]
  idle_timeout = 400

[[vm]]
  memory = '16gb'
  cpu_kind = 'performance'
  cpus = 4
