app = 'spotify-animation'
primary_region = 'arn'

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[http_service.http_options]
  idle_timeout = 400

[[vm]]
  memory = '16gb'
  cpu_kind = 'performance'
  cpus = 4
  
[env]
  APPEND_BATCH_SIZE = "45"
  UPLOAD_FLUSH_SECS = "1.2"
  MIN_UPLOAD_BATCH = "12"
  JPEG_QUALITY = "75"
  OUTPUT_WIDTH = "1280"
  OUTPUT_HEIGHT = "720"
  OUTPUT_DPI = "96"
  UPLOAD_QUEUE_MAX = "90"
  JPEG_SUBSAMPLE = "1"