app = "spotify-animation-encoder"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.http_options]
  idle_timeout = 900

[[checks]]
  name = "health"
  type = "http"
  port = 8080
  interval = "10s"
  timeout = "2s"
  grace_period = "60s"
  method = "GET"
  path = "/health"

[[vm]]
  gpu_kind = "l40s"
  gpus = 1
  cpu_kind = "performance"
  cpus = 4
  memory = "16gb"

[env]
  RENDERER = "agg"
  # Prefer CUDA scaler on Fly (scale_cuda present; NPP not available in this image)
  FFMPEG_SCALER = "cuda"
  NVENC_PRESET = "p4"
  NVENC_RC = "vbr_hq"
  NVENC_CQ = "22"
  NVENC_LOOKAHEAD = "20"
  NVENC_SPATIAL_AQ = "1"
  NVENC_TEMPORAL_AQ = "1"
  NVENC_AQ_STRENGTH = "10"
  NVENC_BFRAMES = "3"
  NVENC_PROFILE = "high"